### ISSUE TITLE
locale name in jade template

### ISSUE THREAD

**Issue by eshikerya** [AdesisNetlife/grunt-jade-i18n#6]
it would be really nice to have locale name available.
I have data configured through yaml file and I pass this data to template. i.e.:

``` yaml
item:
       en:
           title: some title
       es:
           title: algún título
```

so in template I'd like to use something like this:

```
data[$i18n.localeName].title
```

It could be done by adding one line to i18n.coffee file at line 49:
opts.data[namespace].localeName = locale
